id: P9A7FF423
initial_creation_type: input
source_metadata:
  title: Lakṣābhidhānāduddhṛitalaghutantrapiṇḍārthavivaraṇa (block print), colophon
    excerpt
  author: ཕྱག་ན་རྡོ་རྗེ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-07-23); revision in process, thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  text_witnesses: https://sakyaresearch.org/sources/2284
  bases:
    f7cb:
      title: Lakṣābhidhānāduddhṛitalaghutantrapiṇḍārthavivaraṇa (block print), colophon
        excerpt
      order: 1
      base_file: f7cb.txt
created_at: '2022-04-15T18:45:41.149057'
last_modified_at: '2022-04-15T18:45:41.149064'
quality: null
